### ISSUE TITLE
Type-o

### ISSUE THREAD

**Issue by alexander-hagg** [lettucecfd/lettuce-paper#4]
In https://github.com/lettucecfd/lettuce-paper/blob/d79d2a7919b1f6d189fc369ddf9285a4496ce107/02_neural_collision_model/script.py#L106 you write "neuronal net". Please fix to "neural net".

**Comment by Olllom** [comment]
@McBs

**Comment by McBs** [comment]
Thanks @alexander-hagg 

it's fixed.
